from PyQt5 import QtCore, QtGui, QtWidgets

 
class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1259, 983)
        self.label_black = QtWidgets.QLabel(Form)
        self.label_black.setGeometry(QtCore.QRect(0, 0, 1271, 991))
        self.label_black.setStyleSheet("background-color:black;")
        self.label_black.setObjectName("label_black")
        self.back_animation = QtWidgets.QLabel(Form)
        self.back_animation.setGeometry(QtCore.QRect(10, 0, 1251, 991))
        self.back_animation.setText("")
        self.back_animation.setPixmap(QtGui.QPixmap("################image path###############"))
        self.back_animation.setScaledContents(True)
        self.back_animation.setObjectName("back_animation")
        self.voice_input = QtWidgets.QLabel(Form)
        self.voice_input.setGeometry(QtCore.QRect(340, 470, 451, 291))
        self.voice_input.setText("")
        self.voice_input.setPixmap(QtGui.QPixmap("################image path###############"))
        self.voice_input.setScaledContents(True)
        self.voice_input.setObjectName("voice_input")
        self.start_button = QtWidgets.QLabel(Form)
        self.start_button.setGeometry(QtCore.QRect(600, 730, 431, 221))
        self.start_button.setText("")
        self.start_button.setPixmap(QtGui.QPixmap("################image path###############"))
        self.start_button.setScaledContents(True)
        self.start_button.setObjectName("start_button")
        self.side_loding = QtWidgets.QLabel(Form)
        self.side_loding.setGeometry(QtCore.QRect(130, 0, 111, 221))
        self.side_loding.setText("")
        self.side_loding.setPixmap(QtGui.QPixmap("################image path###############"))
        self.side_loding.setScaledContents(True)
        self.side_loding.setObjectName("side_loding")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(180, 750, 451, 141))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("################image path###############"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.bar_loding = QtWidgets.QLabel(Form)
        self.bar_loding.setGeometry(QtCore.QRect(240, 0, 761, 121))
        self.bar_loding.setText("")
        self.bar_loding.setPixmap(QtGui.QPixmap("################image path###############"))
        self.bar_loding.setScaledContents(True)
        self.bar_loding.setObjectName("bar_loding")
        self.human_body = QtWidgets.QLabel(Form)
        self.human_body.setGeometry(QtCore.QRect(610, 110, 401, 361))
        self.human_body.setText("")
        self.human_body.setPixmap(QtGui.QPixmap("################image path###############"))
        self.human_body.setScaledContents(True)
        self.human_body.setObjectName("human_body")
        self.loding_circle = QtWidgets.QLabel(Form)
        self.loding_circle.setGeometry(QtCore.QRect(260, 190, 351, 271))
        self.loding_circle.setText("")
        self.loding_circle.setPixmap(QtGui.QPixmap("################image path###############"))
        self.loding_circle.setScaledContents(True)
        self.loding_circle.setObjectName("loding_circle")
        self.startpushButton = QtWidgets.QPushButton(Form)
        self.startpushButton.setGeometry(QtCore.QRect(732, 837, 161, 51))
        self.startpushButton.setStyleSheet("background-color:transparent;")
        self.startpushButton.setText("")
        self.startpushButton.setObjectName("startpushButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_black.setText(_translate("Form", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
